### ISSUE TITLE
トークン別のスコアの計算法について

### ISSUE THREAD

**Issue by zhongyongriyu** [Ryutaro-A/mlm-scoring-transformers#1]
Ryutaro Asahara様、ディープラーニングを勉強している初心者の鐘（Zhong）です。突然メールを差し上げる失礼のほどお許しください。
大変役立つ日本語文の自然さ検証用のMLM Scoringを開発してくださいまして、どうもありがとうございます。
ご説明に従って文全体のスコアの計算はできましたが、トークン別にスコアを計算してプリントアウトすることはできませんでしょうか。もしできれば、その計算法を教えていただけませんでしょうか。

**Comment by Ryutaro-A** [comment]
Zhongさん

ご連絡ありがとうございます．
利用していただき嬉しく思います．

返信が遅くなってしまいましたが，「トークン別にスコアを計算してプリントアウト」が可能なメソッドを実装予定です．

もうしばらくお待ち下さい．

**Comment by zhongyongriyu** [comment]
Asaharaさん
ご返信どうもありがとうございます。
ご実装を楽しみにしております。

**Comment by Ryutaro-A** [comment]
Zhongさん

ご要望のあったトークンごとのスコアを取得するためのオプションを追加しました．
READMEに使用方法を追記したので，ご利用ください．

バグなどがありましたら報告いただけると嬉しいです．

**Comment by zhongyongriyu** [comment]
Asaharaさん
早速トークンごとのスコアを取得してみました。
上手くいきました。
どうもありがとうございました。
これからいっぱい活用させていただきます。
